version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: nfc-postgres
    restart: always
    environment:
      POSTGRES_USER: neuro
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nfc-blog-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nfc-network

volumes:
  postgres_data:

networks:
  nfc-network:
    driver: bridge
