version: "3.9"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfc-blogsite-nextjs
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_USE_EMULATOR: "true"
      NEXT_PUBLIC_FIREBASE_EMULATOR_FIRESTORE: "http://host.docker.internal:9090"
      NEXT_PUBLIC_FIREBASE_EMULATOR_AUTH: "http://host.docker.internal:9099"
      NEXT_PUBLIC_FIREBASE_EMULATOR_STORAGE: "http://host.docker.internal:9199"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - nfc-network

networks:
  nfc-network:
    driver: bridge
